In [11]:
from pathlib import Path

import pandas as pd

SILVER_SECURITY_PATH = Path("../../data/silver/securite_data_silver_clean.csv")
GOLD_DIR = Path("../../data/gold/security")

print(f"Chargement du fichier : {SILVER_SECURITY_PATH}")
df_sec = pd.read_csv(SILVER_SECURITY_PATH, sep=";", dtype=str)

display(df_sec.head())
print(df_sec.shape)

Chargement du fichier : ../../data/silver/securite_data_silver_clean.csv

,code_departement,code_commune,code_insee_commune,annee,indicateur,unite_de_compte,nombre,taux_pour_mille,est_diffuse,insee_pop,insee_pop_millesime,insee_log,insee_log_millesime,complement_info_nombre,complement_info_taux,source_dataset,source_dataset_timestamp,date_refresh
0,69,001,69001,2016,Violences physiques intrafamiliales,Victime,0.0,0.0,diff,358,2016-01-01,163,2016-01-01,0.0,0.0,securite_commune,2026-03-23 14:13:09.597346,2026-03-23
1,69,001,69001,2016,Violences physiques hors cadre familial,Victime,0.0,0.0,diff,358,2016-01-01,163,2016-01-01,0.0,0.0,securite_commune,2026-03-23 14:13:09.597346,2026-03-23
2,69,001,69001,2016,Violences sexuelles,Victime,0.0,0.0,diff,358,2016-01-01,163,2016-01-01,0.0,0.0,securite_commune,2026-03-23 14:13:09.597346,2026-03-23
3,69,001,69001,2016,Vols avec armes,Infraction,0.0,0.0,diff,358,2016-01-01,163,2016-01-01,0.0,0.0,securite_commune,2026-03-23 14:13:09.597346,2026-03-23
4,69,001,69001,2016,Vols violents sans arme,Infraction,1.5816327,0.3170966,ndiff,358,2016-01-01,163,2016-01-01,1.5816327,0.3170966,securite_commune,2026-03-23 14:13:09.597346,2026-03-23

(37125, 18)

In [12]:
# Normalisation des cles et des types pour alignement avec le modele Gold existant

df_sec = df_sec.copy()

df_sec["code_departement"] = df_sec["code_departement"].astype(str).str.strip().str.zfill(2)
df_sec["code_commune"] = df_sec["code_commune"].astype(str).str.strip().str.zfill(3)
df_sec["code_insee_commune"] = df_sec["code_insee_commune"].astype(str).str.strip().str.zfill(5)

df_sec["annee"] = pd.to_numeric(df_sec["annee"], errors="coerce").astype("Int64")
df_sec["nombre"] = pd.to_numeric(df_sec["nombre"], errors="coerce")
df_sec["taux_pour_mille"] = pd.to_numeric(df_sec["taux_pour_mille"], errors="coerce")
df_sec["insee_pop"] = pd.to_numeric(df_sec["insee_pop"], errors="coerce").astype("Int64")
df_sec["insee_log"] = pd.to_numeric(df_sec["insee_log"], errors="coerce").astype("Int64")
df_sec["complement_info_nombre"] = pd.to_numeric(df_sec["complement_info_nombre"], errors="coerce")
df_sec["complement_info_taux"] = pd.to_numeric(df_sec["complement_info_taux"], errors="coerce")

df_sec["source_dataset_timestamp"] = pd.to_datetime(df_sec["source_dataset_timestamp"], errors="coerce")
df_sec["date_refresh"] = pd.to_datetime(df_sec["date_refresh"], errors="coerce")

df_sec["indicateur"] = df_sec["indicateur"].astype(str).str.strip()
df_sec["unite_de_compte"] = df_sec["unite_de_compte"].astype(str).str.strip()
df_sec["est_diffuse"] = df_sec["est_diffuse"].astype(str).str.strip()
df_sec["source_dataset"] = df_sec["source_dataset"].astype(str).str.strip()

df_sec["id_commune"] = df_sec["code_departement"] + "-" + df_sec["code_commune"]

display(df_sec.head())
print(df_sec.dtypes)

,code_departement,code_commune,code_insee_commune,annee,indicateur,unite_de_compte,nombre,taux_pour_mille,est_diffuse,insee_pop,insee_pop_millesime,insee_log,insee_log_millesime,complement_info_nombre,complement_info_taux,source_dataset,source_dataset_timestamp,date_refresh,id_commune
0,69,001,69001,2016,Violences physiques intrafamiliales,Victime,0.000000,0.000000,diff,358,2016-01-01,163,2016-01-01,0.000000,0.000000,securite_commune,2026-03-23 14:13:09.597346,2026-03-23,69-001
1,69,001,69001,2016,Violences physiques hors cadre familial,Victime,0.000000,0.000000,diff,358,2016-01-01,163,2016-01-01,0.000000,0.000000,securite_commune,2026-03-23 14:13:09.597346,2026-03-23,69-001
2,69,001,69001,2016,Violences sexuelles,Victime,0.000000,0.000000,diff,358,2016-01-01,163,2016-01-01,0.000000,0.000000,securite_commune,2026-03-23 14:13:09.597346,2026-03-23,69-001
3,69,001,69001,2016,Vols avec armes,Infraction,0.000000,0.000000,diff,358,2016-01-01,163,2016-01-01,0.000000,0.000000,securite_commune,2026-03-23 14:13:09.597346,2026-03-23,69-001
4,69,001,69001,2016,Vols violents sans arme,Infraction,1.581633,0.317097,ndiff,358,2016-01-01,163,2016-01-01,1.581633,0.317097,securite_commune,2026-03-23 14:13:09.597346,2026-03-23,69-001

code_departement                    object
code_commune                        object
code_insee_commune                  object
annee                                Int64
indicateur                          object
unite_de_compte                     object
nombre                             float64
taux_pour_mille                    float64
est_diffuse                         object
insee_pop                            Int64
insee_pop_millesime                 object
insee_log                            Int64
insee_log_millesime                 object
complement_info_nombre             float64
complement_info_taux               float64
source_dataset                      object
source_dataset_timestamp    datetime64[ns]
date_refresh                datetime64[ns]
id_commune                          object
dtype: object

In [13]:
# Construction de la dimension des indicateurs de securite

dim_indicateur_securite = (
    df_sec[["indicateur", "unite_de_compte"]]
    .drop_duplicates()
    .sort_values(["indicateur", "unite_de_compte"])
    .reset_index(drop=True)
)

dim_indicateur_securite["id_indicateur_securite"] = [
    f"SEC_{i:03d}" for i in range(1, len(dim_indicateur_securite) + 1)
]

dim_indicateur_securite = dim_indicateur_securite[[
    "id_indicateur_securite",
    "indicateur",
    "unite_de_compte",
]]

display(dim_indicateur_securite.head())
print(dim_indicateur_securite.shape)

,id_indicateur_securite,indicateur,unite_de_compte
0,SEC_001,Cambriolages de logement,Infraction
1,SEC_002,Destructions et dégradations volontaires,Infraction
2,SEC_003,Escroqueries et fraudes aux moyens de paiement,Victime
3,SEC_004,Trafic de stupéfiants,Mis en cause
4,SEC_005,Usage de stupéfiants,Mis en cause

(15, 3)

In [14]:
# Construction de la table de faits securite au grain commune + annee + indicateur

fact_securite = df_sec.merge(
    dim_indicateur_securite,
    on=["indicateur", "unite_de_compte"],
    how="left"
)

fact_securite = fact_securite[[
    "id_commune",
    "annee",
    "id_indicateur_securite",
    "code_departement",
    "code_commune",
    "code_insee_commune",
    "nombre",
    "taux_pour_mille",
    "est_diffuse",
    "insee_pop",
    "insee_log",
    "complement_info_nombre",
    "complement_info_taux",
    "source_dataset",
    "source_dataset_timestamp",
    "date_refresh",
]]

fact_securite = fact_securite.sort_values([
    "code_departement",
    "code_commune",
    "annee",
    "id_indicateur_securite",
]).reset_index(drop=True)

display(fact_securite.head())
print(fact_securite.shape)

,id_commune,annee,id_indicateur_securite,code_departement,code_commune,code_insee_commune,nombre,taux_pour_mille,est_diffuse,insee_pop,insee_log,complement_info_nombre,complement_info_taux,source_dataset,source_dataset_timestamp,date_refresh
0,69-001,2016,SEC_001,69,001,69001,3.392593,6.780636,ndiff,358,163,3.392593,6.780636,securite_commune,2026-03-23 14:13:09.597346,2026-03-23
1,69-001,2016,SEC_002,69,001,69001,2.951613,3.344787,ndiff,358,163,2.951613,3.344787,securite_commune,2026-03-23 14:13:09.597346,2026-03-23
2,69-001,2016,SEC_003,69,001,69001,2.664429,2.651935,ndiff,358,163,2.664429,2.651935,securite_commune,2026-03-23 14:13:09.597346,2026-03-23
3,69-001,2016,SEC_004,69,001,69001,0.000000,0.000000,diff,358,163,0.000000,0.000000,securite_commune,2026-03-23 14:13:09.597346,2026-03-23
4,69-001,2016,SEC_005,69,001,69001,3.613497,1.736679,ndiff,358,163,3.613497,1.736679,securite_commune,2026-03-23 14:13:09.597346,2026-03-23

(37125, 16)

In [15]:
# Sauvegarde des tables Gold securite

GOLD_DIR.mkdir(parents=True, exist_ok=True)

dim_output_path = GOLD_DIR / "dim_indicateur_securite.csv"
fact_output_path = GOLD_DIR / "fact_securite.csv"

dim_indicateur_securite.to_csv(dim_output_path, sep=";", index=False)
fact_securite.to_csv(fact_output_path, sep=";", index=False)

print(f"Dimension sauvegardee : {dim_output_path}")
print(f"Fact sauvegardee : {fact_output_path}")

Dimension sauvegardee : ../../data/gold/security/dim_indicateur_securite.csv
Fact sauvegardee : ../../data/gold/security/fact_securite.csv