In [15]:
from pathlib import Path
import pandas as pd

pd.set_option("display.max_rows", 500)
pd.set_option("display.max_columns", 500)

In [16]:
project_root = Path.cwd().resolve()
while not (project_root / "data").exists() and project_root != project_root.parent:
    project_root = project_root.parent

bronze_path = project_root / "data" / "bronze" / "bronze_burvot_t2_rhone_69.csv"
silver_commune_path = project_root / "data" / "silver" / "silver_burvot_t2_rhone_69_commune.csv"
silver_candidate_path = project_root / "data" / "silver" / "silver_burvot_t2_rhone_69_candidate.csv"

silver_commune_path.parent.mkdir(parents=True, exist_ok=True)

In [17]:
df = pd.read_csv(
    bronze_path,
    sep=";",
    dtype=str,
    encoding="utf-8"
)

df.columns = [c.strip() for c in df.columns]
display(df.head())

# Fix broken unnamed columns
rename_map = {
    "Unnamed: 26": "N°Panneau.1",
    "Unnamed: 27": "Sexe.1",
    "Unnamed: 28": "Nom.1",
    "Unnamed: 29": "Prénom.1",
    "Unnamed: 30": "Voix.1",
    "Unnamed: 31": "% Voix/Ins.1",
    "Unnamed: 32": "% Voix/Exp.1",
}
df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns})

display(df.head())

,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Etat saisie,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,% Blancs/Vot,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,N°Panneau,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,extraction_source_url,ingestion_timestamp,source_file_name
0,69,Rhône,001,Affoux,Complet,316,49,15.51,267,84.49,21,6.65,7.87,9,2.85,3.37,237,75,88.76,1,M,MACRON,Emmanuel,98,31.01,41.35,2,F,LE PEN,Marine,139,43.99,58.65,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
1,69,Rhône,002,Aigueperse,Complet,217,47,21.66,170,78.34,9,4.15,5.29,4,1.84,2.35,157,72.35,92.35,1,M,MACRON,Emmanuel,74,34.1,47.13,2,F,LE PEN,Marine,83,38.25,52.87,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
2,69,Rhône,003,Albigny-sur-Saône,Complet,1860,504,27.1,1356,72.9,81,4.35,5.97,18,0.97,1.33,1257,67.58,92.7,1,M,MACRON,Emmanuel,823,44.25,65.47,2,F,LE PEN,Marine,434,23.33,34.53,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
3,69,Rhône,004,Alix,Complet,470,95,20.21,375,79.79,35,7.45,9.33,4,0.85,1.07,336,71.49,89.6,1,M,MACRON,Emmanuel,194,41.28,57.74,2,F,LE PEN,Marine,142,30.21,42.26,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
4,69,Rhône,005,Ambérieux,Complet,407,62,15.23,345,84.77,10,2.46,2.9,3,0.74,0.87,332,81.57,96.23,1,M,MACRON,Emmanuel,151,37.1,45.48,2,F,LE PEN,Marine,181,44.47,54.52,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx

,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Etat saisie,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,% Blancs/Vot,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,N°Panneau,Sexe,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,N°Panneau.1,Sexe.1,Nom.1,Prénom.1,Voix.1,% Voix/Ins.1,% Voix/Exp.1,extraction_source_url,ingestion_timestamp,source_file_name
0,69,Rhône,001,Affoux,Complet,316,49,15.51,267,84.49,21,6.65,7.87,9,2.85,3.37,237,75,88.76,1,M,MACRON,Emmanuel,98,31.01,41.35,2,F,LE PEN,Marine,139,43.99,58.65,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
1,69,Rhône,002,Aigueperse,Complet,217,47,21.66,170,78.34,9,4.15,5.29,4,1.84,2.35,157,72.35,92.35,1,M,MACRON,Emmanuel,74,34.1,47.13,2,F,LE PEN,Marine,83,38.25,52.87,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
2,69,Rhône,003,Albigny-sur-Saône,Complet,1860,504,27.1,1356,72.9,81,4.35,5.97,18,0.97,1.33,1257,67.58,92.7,1,M,MACRON,Emmanuel,823,44.25,65.47,2,F,LE PEN,Marine,434,23.33,34.53,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
3,69,Rhône,004,Alix,Complet,470,95,20.21,375,79.79,35,7.45,9.33,4,0.85,1.07,336,71.49,89.6,1,M,MACRON,Emmanuel,194,41.28,57.74,2,F,LE PEN,Marine,142,30.21,42.26,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
4,69,Rhône,005,Ambérieux,Complet,407,62,15.23,345,84.77,10,2.46,2.9,3,0.74,0.87,332,81.57,96.23,1,M,MACRON,Emmanuel,151,37.1,45.48,2,F,LE PEN,Marine,181,44.47,54.52,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx

In [18]:
def clean_string(series: pd.Series) -> pd.Series:
    return series.astype("string").str.strip()

def to_int_nullable(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series, errors="coerce").astype("Int64")

def to_float_nullable(series: pd.Series) -> pd.Series:
    return pd.to_numeric(
        series.astype("string").str.replace(",", ".", regex=False),
        errors="coerce"
    ).astype("Float64")

In [19]:
# Clean identifiers / strings
string_cols = [
    "Code du département",
    "Libellé du département",
    "Code de la commune",
    "Libellé de la commune",
    "Etat saisie",
    "Sexe",
    "Nom",
    "Prénom",
    "Sexe.1",
    "Nom.1",
    "Prénom.1",
    "extraction_source_url",
    "ingestion_timestamp",
    "source_file_name",
]

for col in string_cols:
    if col in df.columns:
        df[col] = clean_string(df[col])

# preserve leading zeros
if "Code du département" in df.columns:
    df["Code du département"] = df["Code du département"].str.zfill(2)

if "Code de la commune" in df.columns:
    df["Code de la commune"] = df["Code de la commune"].str.zfill(3)


# Cast commune-level numerics
commune_int_cols = [
    "Inscrits",
    "Abstentions",
    "Votants",
    "Blancs",
    "Nuls",
    "Exprimés",
]

commune_float_cols = [
    "% Abs/Ins",
    "% Vot/Ins",
    "% Blancs/Ins",
    "% Blancs/Vot",
    "% Nuls/Ins",
    "% Nuls/Vot",
    "% Exp/Ins",
    "% Exp/Vot",
]

for col in commune_int_cols:
    if col in df.columns:
        df[col] = to_int_nullable(df[col])

for col in commune_float_cols:
    if col in df.columns:
        df[col] = to_float_nullable(df[col])

In [ ]:
# Build commune-level silver

commune_cols = [
    "Code du département",
    "Libellé du département",
    "Code de la commune",
    "Libellé de la commune",
    "Etat saisie",
    "Inscrits",
    "Abstentions",
    "% Abs/Ins",
    "Votants",
    "% Vot/Ins",
    "Blancs",
    "% Blancs/Ins",
    "% Blancs/Vot",
    "Nuls",
    "% Nuls/Ins",
    "% Nuls/Vot",
    "Exprimés",
    "% Exp/Ins",
    "% Exp/Vot",
    "extraction_source_url",
    "ingestion_timestamp",
    "source_file_name",
]
commune_cols = [c for c in commune_cols if c in df.columns]
df_commune = df[commune_cols].copy()

df_commune["commune_id"] = (
    df_commune["Code du département"].fillna("") + "_"
    + df_commune["Code de la commune"].fillna("")
)

df_commune = df_commune[["commune_id"] + [c for c in df_commune.columns if c != "commune_id"]]
df_commune = df_commune.drop_duplicates(subset=["commune_id"]).reset_index(drop=True)

In [ ]:
# Build candidate-level silver

candidate_rows = []
suffixes = ["", ".1"]

for suffix in suffixes:
    panneau_col = f"N°Panneau{suffix}"
    sexe_col = f"Sexe{suffix}"
    nom_col = f"Nom{suffix}"
    prenom_col = f"Prénom{suffix}"
    voix_col = f"Voix{suffix}"
    pct_ins_col = f"% Voix/Ins{suffix}"
    pct_exp_col = f"% Voix/Exp{suffix}"

    needed = [panneau_col, sexe_col, nom_col, prenom_col, voix_col, pct_ins_col, pct_exp_col]
    if not all(col in df.columns for col in needed):
        continue

    temp = pd.DataFrame({
        "commune_id": (
            df["Code du département"].fillna("").astype("string") + "_"
            + df["Code de la commune"].fillna("").astype("string")
        ),
        "candidate_slot": ".0" if suffix == "" else suffix,
        "numero_panneau": to_int_nullable(df[panneau_col]),
        "sexe": clean_string(df[sexe_col]),
        "nom": clean_string(df[nom_col]),
        "prenom": clean_string(df[prenom_col]),
        "voix": to_int_nullable(df[voix_col]),
        "pct_voix_ins": to_float_nullable(df[pct_ins_col]),
        "pct_voix_exp": to_float_nullable(df[pct_exp_col]),
        "extraction_source_url": clean_string(df["extraction_source_url"]),
        "ingestion_timestamp": clean_string(df["ingestion_timestamp"]),
        "source_file_name": clean_string(df["source_file_name"]),
    })

    candidate_rows.append(temp)

In [22]:
df_candidate = pd.concat(candidate_rows, ignore_index=True)

df_candidate = df_candidate[
    ~(
        df_candidate["numero_panneau"].isna()
        & df_candidate["nom"].isna()
        & df_candidate["prenom"].isna()
    )
].copy()

df_candidate["candidate_id"] = (
    df_candidate["numero_panneau"].astype("string").fillna("") + "_"
    + df_candidate["nom"].fillna("") + "_"
    + df_candidate["prenom"].fillna("")
)

candidate_cols = [
    "commune_id",
    "candidate_id",
    "candidate_slot",
    "numero_panneau",
    "sexe",
    "nom",
    "prenom",
    "voix",
    "pct_voix_ins",
    "pct_voix_exp",
    "extraction_source_url",
    "ingestion_timestamp",
    "source_file_name",
]
df_candidate = df_candidate[candidate_cols].reset_index(drop=True)

In [23]:
df_commune.to_csv(silver_commune_path, sep=";", index=False, encoding="utf-8")
df_candidate.to_csv(silver_candidate_path, sep=";", index=False, encoding="utf-8")

print(f"Wrote commune silver: {silver_commune_path}")
print(f"Wrote candidate silver: {silver_candidate_path}")

print("\nCOMMUNE SHAPE:", df_commune.shape)
print("CANDIDATE SHAPE:", df_candidate.shape)

print("\nCOMMUNE SAMPLE:")
display(df_commune.head())

print("\nCANDIDATE SAMPLE:")
display(df_candidate.head(10))

Wrote commune silver: /Users/zainfrayha/Documents/EPSI/MSPR/electio-analytics-poc/data/silver/silver_burvot_t2_rhone_69_commune.csv
Wrote candidate silver: /Users/zainfrayha/Documents/EPSI/MSPR/electio-analytics-poc/data/silver/silver_burvot_t2_rhone_69_candidate.csv

COMMUNE SHAPE: (267, 23)
CANDIDATE SHAPE: (534, 13)

COMMUNE SAMPLE:

,commune_id,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Etat saisie,Inscrits,Abstentions,% Abs/Ins,Votants,% Vot/Ins,Blancs,% Blancs/Ins,% Blancs/Vot,Nuls,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,extraction_source_url,ingestion_timestamp,source_file_name
0,69_001,69,Rhône,001,Affoux,Complet,316,49,15.51,267,84.49,21,6.65,7.87,9,2.85,3.37,237,75.0,88.76,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
1,69_002,69,Rhône,002,Aigueperse,Complet,217,47,21.66,170,78.34,9,4.15,5.29,4,1.84,2.35,157,72.35,92.35,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
2,69_003,69,Rhône,003,Albigny-sur-Saône,Complet,1860,504,27.1,1356,72.9,81,4.35,5.97,18,0.97,1.33,1257,67.58,92.7,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
3,69_004,69,Rhône,004,Alix,Complet,470,95,20.21,375,79.79,35,7.45,9.33,4,0.85,1.07,336,71.49,89.6,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
4,69_005,69,Rhône,005,Ambérieux,Complet,407,62,15.23,345,84.77,10,2.46,2.9,3,0.74,0.87,332,81.57,96.23,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx

CANDIDATE SAMPLE:

,commune_id,candidate_id,candidate_slot,numero_panneau,sexe,nom,prenom,voix,pct_voix_ins,pct_voix_exp,extraction_source_url,ingestion_timestamp,source_file_name
0,69_001,1_MACRON_Emmanuel,.0,1,M,MACRON,Emmanuel,98,31.01,41.35,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
1,69_002,1_MACRON_Emmanuel,.0,1,M,MACRON,Emmanuel,74,34.1,47.13,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
2,69_003,1_MACRON_Emmanuel,.0,1,M,MACRON,Emmanuel,823,44.25,65.47,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
3,69_004,1_MACRON_Emmanuel,.0,1,M,MACRON,Emmanuel,194,41.28,57.74,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
4,69_005,1_MACRON_Emmanuel,.0,1,M,MACRON,Emmanuel,151,37.1,45.48,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
5,69_006,1_MACRON_Emmanuel,.0,1,M,MACRON,Emmanuel,1281,36.54,53.15,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
6,69_007,1_MACRON_Emmanuel,.0,1,M,MACRON,Emmanuel,784,36.67,50.94,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
7,69_008,1_MACRON_Emmanuel,.0,1,M,MACRON,Emmanuel,207,41.9,53.63,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
8,69_009,1_MACRON_Emmanuel,.0,1,M,MACRON,Emmanuel,2218,43.84,64.05,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx
9,69_010,1_MACRON_Emmanuel,.0,1,M,MACRON,Emmanuel,1735,41.59,63.37,https://www.data.gouv.fr/api/1/datasets/r/06d9...,2026-03-07T23:24:07.583940,burvot_t2_france_entiere.xlsx