In [16]:
import pandas as pd
import numpy as np
import os
import requests
from datetime import datetime

pd.set_option('display.max_rows', 500)

In [17]:
# ── 1. PATH CONFIGURATION ───────────────
BASE_DATA_DIR = "../../../data"

RAW_DIR    = os.path.join(BASE_DATA_DIR, "raw")
BRONZE_DIR = os.path.join(BASE_DATA_DIR, "bronze")

os.makedirs(RAW_DIR, exist_ok=True)
os.makedirs(BRONZE_DIR, exist_ok=True)

CSV_URL = "https://www.data.gouv.fr/api/1/datasets/r/6fd17a6c-519b-465c-a7fd-ad2955fafc76"

path_csv_raw         = os.path.join(RAW_DIR, "dictionnaire des nuances politiques.csv")
path_communes_bronze = os.path.join(BRONZE_DIR, "bronze_dictionnaire_des_nuances_politiques.csv")

In [18]:
# ── 2. RAW LAYER: Landing Zone ──────────────────────────────────────────────
# We keep the source file exactly as it is.
if not os.path.exists(path_csv_raw):
    print(f"📥 Downloading source to RAW...")
    resp = requests.get(CSV_URL, timeout=180)
    resp.raise_for_status()
    with open(path_csv_raw, "wb") as f:
        f.write(resp.content)
    print(f"✅ Saved to RAW: {path_csv_raw}")
else:
    print(f"✅ Raw file already exists in {RAW_DIR}")

✅ Raw file already exists in ../../../data/raw

In [19]:
# ── 3. BRONZE LAYER: Ingestion & Metadata ───────────────────────────────────
# Bronze is for "raw-ish" data in a readable format with audit columns.
print("\n🛠 Processing RAW -> BRONZE...")
df_bronze = pd.read_csv(path_csv_raw, sep=None, engine="python", dtype=str)

# Normalize column names by trimming surrounding spaces
df_bronze.columns = [c.strip() if isinstance(c, str) else c for c in df_bronze.columns]
df_bronze['extraction_source_url'] = CSV_URL
df_bronze['ingestion_timestamp']   = datetime.now().isoformat()
df_bronze['source_file_name']      = os.path.basename(path_csv_raw)

🛠 Processing RAW -> BRONZE...

In [20]:
display(df_bronze.head())

,Nuance,Libellé,extraction_source_url,ingestion_timestamp,source_file_name
0,EXG,Extrême gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
1,COM,Communiste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
2,PG,Parti de Gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
3,SOC,Socialiste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
4,RDG,Radical de Gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv

In [21]:
# --- Ajout manuel de nuances (sans modifier le reste du pipeline) ---

nouvelles_nuances = pd.DataFrame([
    {"Nuance": "RES", "Libellé": "Résistons !"},
    {"Nuance": "MODEM", "Libellé": "Mouvement démocrate"},
    {"Nuance": "EELV", "Libellé": "Europe Écologie Les Verts"}
])

# Ajouter les métadonnées demandées
nouvelles_nuances["extraction_source_url"] = "manual_correction"
nouvelles_nuances["ingestion_timestamp"] = datetime.now().isoformat()
nouvelles_nuances["source_file_name"] = "manual_correction"

# Ajouter au dataset principal
df_bronze = pd.concat([df_bronze, nouvelles_nuances], ignore_index=True)
display(df_bronze)

,Nuance,Libellé,extraction_source_url,ingestion_timestamp,source_file_name
0,EXG,Extrême gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
1,COM,Communiste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
2,PG,Parti de Gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
3,SOC,Socialiste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
4,RDG,Radical de Gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
5,DVG,Divers gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
6,VEC,Europe Ecologie / Les Verts,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
7,ECO,Ecologiste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
8,REG,Régionaliste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
9,AUT,Autres,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
10,MODM,MODEM,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
11,M-NC,Majorité présidentielle,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
12,M,Autres candidats majorité présidentielle,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
13,UMP,Union pour un Mouvement Populaire,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
14,DVD,Divers droite,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
15,FN,Front National,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
16,EXD,Extrême droite,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
17,LEXG,Liste d'extrême-gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
18,LCOP,Liste du PCF et du Parti de gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
19,LSOC,Liste du Parti socialiste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
20,LDVG,Liste divers gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
21,LVEC,Liste des Verts,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
22,LREG,Liste régionaliste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
23,LAUT,Autre liste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
24,LCMD,Liste centre-MoDem,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
25,LMAJ,Liste de la majorité,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
26,LDVD,Liste divers droite,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
27,LDSV,Liste souverainiste de droite,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
28,LFN,Liste du Front national,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
29,LEXD,Liste d'extrême-droite,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
30,LFG,Liste Front de Gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
31,LPG,Liste du Parti de Gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
32,LCOM,Liste du Parti communiste français,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
33,LUG,Liste Union de la Gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
34,LDIV,Liste Divers,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
35,LMDM,Liste Modem,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
36,LUC,Liste Union du Centre,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
37,LUDI,Liste Union Démocrates et Indépendants,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
38,LUMP,Liste Union pour un Mouvement Populaire,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
39,LUD,Liste Union de la Droite,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
40,CPNT,Chasse Pêche Nature Traditions,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
41,DIV,Divers,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
42,UDFD,UDF-Mouvement Démocrate,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
43,MAJ,Majorité présidentielle,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
44,MPF,Mouvement pour la France,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
45,FG,Front de gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
46,CEN,Le Centre pour la France,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
47,ALLI,Alliance centriste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
48,PRV,Parti radical,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
49,NCE,Nouveau Centre,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
50,FI,La France insoumise,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
51,REM,La République en marche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
52,MDM,Modem,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
53,UDI,Union des Démocrates et Indépendants,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
54,LR,Les Républicains,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
55,DLF,Debout la France,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
56,DXG,Divers extrême gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
57,NUP,Nouvelle union populaire écologique et sociale,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
58,ENS,Ensemble ! (Majorité présidentielle),https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
59,DVC,Divers centre,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
60,DSV,Droite souverainiste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
61,REC,Reconquête !,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
62,RN,Rassemblement National,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
63,DXD,Divers extrême droite,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
64,LFI,La France insoumise,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
65,LRDG,Parti radical de gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
66,LECO,Ecologiste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
67,LGJ,Gilets jaunes,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
68,LREM,La République en marche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
69,LDVC,Divers centre,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
70,LLR,Les Républicains,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
71,LDLF,Debout la France,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
72,LRN,Rassemblement National,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
73,LGC,Liste gauche-centristes,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
74,LMC,Liste majorité-centristes,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
75,LNC,Non Communiqué,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
76,LVEG,Liste EELV et gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
77,LUGE,Liste d'union à gauche avec des écologiste,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
78,LUCG,Liste d'union au centre et à gauche,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
79,LUCD,Liste d'union au centre et à droite,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
80,LUXD,Liste d'union à l'extrême-droite,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
81,LMMD,Liste Majorité-MoDem,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
82,LCEN,Liste d'union du centre,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
83,LDLR,Liste Debout la République,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
84,DLR,Debout la République,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
85,LMP,Majorité présidentielle,https://www.data.gouv.fr/api/1/datasets/r/6fd1...,2026-03-28T22:27:49.891940,dictionnaire des nuances politiques.csv
86,RES,Résistons !,manual_correction,2026-03-28T22:27:49.915592,manual_correction
87,MODEM,Mouvement démocrate,manual_correction,2026-03-28T22:27:49.915592,manual_correction
88,EELV,Europe Écologie Les Verts,manual_correction,2026-03-28T22:27:49.915592,manual_correction

In [22]:
df_bronze.to_csv(path_communes_bronze, index=False, sep=";", encoding="utf-8")

print(f"✅ BRONZE dataset created: {path_communes_bronze}")
print(f"📊 Rows: {len(df_bronze)} | Columns: {len(df_bronze.columns)}")

✅ BRONZE dataset created: ../../../data/bronze/bronze_dictionnaire_des_nuances_politiques.csv
📊 Rows: 89 | Columns: 5